# General

set -g default-command "/bin/zsh"
set -g default-terminal "tmux-256color"
set -g set-titles on
set -g set-titles-string "#{pane-title}"

# Prefix

set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Reload configuration

unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Mouse & Keyboard

set -g mouse on
setw -g mode-keys vi

# History

set -g history-limit 100000

# Pane Navigation

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize panes

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Maximize / restore current pane

bind z resize-pane -Z

# Kill current pane without confirmation

bind x kill-pane

# Pane Splitting

unbind '"'
bind '\' split-window -h -c "#{pane_current_path}"
unbind '%'
bind - split-window -v -c "#{pane_current_path}"

# New window in current directory

bind c new-window -c "#{pane_current_path}"

# Server Options

set -s focus-events on
set -s extended-keys on
set -s escape-time 0

# Copy mode

setw -g mode-keys vi

# Window & Pane Indexing

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Vim-style window navigation

bind -n C-h previous-window
bind -n C-l next-window

# Status Line Colors

DARKMASTER="#282c34"
BASEDARK="#2c323c"
FGLIGHT="#a9b0bd"
DARKGRAY="#3e4452"
DIMGRAY="#657079"
GREEN="#98c379"

# Status Line Style

set -g status-position bottom
set -g status-style "bg=${BASEDARK}"
set -g status-justify absolute-centre

set -g status-left-length 100
set -g status-left "#[bg=${DARKGRAY}] #{=21:pane_title} "

set -g window-status-format "#[fg=${DIMGRAY}]#I.#W"
set -g window-status-current-format "#[fg=${FGLIGHT}]#I.#W"
set -g window-status-separator "#[fg=${DIMGRAY}] | "

set -g status-right-length 100
set -g status-right "#[bg=${DARKGRAY}] #S "

# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navikator'
set -g @plugin 'tmux-plugins/tmux-cpu'

# TPM

run '~/.tmux/plugins/tpm/tpm'
